### PR TITLE
add --always to describe

### PR DESCRIPTION
**Pull request by e-e-e**
At the moment git:describe fails with `fatal: No names found, cannot describe anything.` if the git repository does not contain any names. 

I added `--always` to the git describe command so that it will not fail in these cases and will instead revert to short hash.

### CODE REVIEW

**Comment by e-e-e** [comment]
Ah I see now that the tests are failing you expect this behaviour. Is this something that you would be willing to change or is there a reason for failing in this case?

**Comment by e-e-e** [comment]
@jacob-meacham oh wonderful - I will modify this PR when I get some time today. Thanks.

**Comment by e-e-e** [comment]
Tests should be fixed now @jacob-meacham if you want to take another look.

**Comment by e-e-e** [comment]
When this is ready to merge is it possible to release a new version with this change and https://github.com/jacob-meacham/serverless-plugin-git-variables/pull/10?

**Comment by jacob-meacham** [comment]
@e-e-e released as 3.0.0. Thanks!

**Pull request merged**
